@startuml
Client -> API: Data Import Request

API -> JobLauncher: start importMemberJob
'JobLauncher 에 배치 작업 시작 지시

JobLauncher --> Job: jobExecution()
JobLauncher --> Job: createJobInstance()
JobLauncher --> Job: getJobRepository()
'작업 상태 관리 -> 배치 처음 실행시키면 생성되는 테이블들로 관리된다.
'각 작업의 status, 생성된 instance 들의 정보를 가지고 있다.
JobLauncher --> Job: executeJob()

Job --> Step : start importMemberStep
Job --> Step : start transaction
Job --> Step : ItemReader.read() - fileReader
'입력된 csv, 엑셀 데이터 읽고 MemberForFileRequest 타입으로 반환
Job --> Step : ItemProcessor.process() - processor
'MemberForFileRequest -> Member'로 형변환
Job --> Step : ItemWriter.process() - jpaWriter
'Member 타입으로 변환된 데이터를 Jpa를 통해 DB에 저장함
Job --> Step : commit
'step이 실행될 동안 반환된 에러가 없다면 데이터 커밋

Step --> Job : stepComplete

Job --> JobLauncher : JobComplete
'importMemberJob 의 모든 step 이 완료되었음

JobLauncher -> API : JobCompletion
'작업이 완료된 이후 리스너로 처리가 가능하지만 service 단에서 관리하도록 구현

API -> Client : Response 200


@enduml
