name: Deploy interp.ia API

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

env:
  APPLICATION_NAME: interp.log.api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: SSH to server, run build script and restart application services
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: APPLICATION_NAME
        script: |
          # Create Git tag, build and push Docker image
          cd /home/ubuntu/interp/interp.deployment/scripts/$APPLICATION_NAME.sh
          chmod +x ./$APPLICATION_NAME.sh
          ./$APPLICATION_NAME.sh
          
          # Restart the Docker containers
          cd /home/ubuntu/interp
          docker compose down
          docker compose pull
          docker compose up -d
